name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello Step
        run: echo "Hello, world!"

      - name: 23f3002663@ds.study.iitm.ac.in
        run: echo "Email step"
